[package]
name = "hack_assembler"
version = "0.1.0"
authors = ["mitoma <mutetheradio@gmail.com>"]
edition = "2021"

[[bin]]
name = "assembler"
path = "src/assembler.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
