name: Continuous integration

on: [push, pull_request]

jobs:

  check-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mitoma/sver-actions/setup@support-restore-only
      - name: echo branch
        run: |
          echo "github.ref"
          echo ${{ github.ref }}
          echo "default_branch"
          echo ${{ github.event.repository.default_branch }}
          echo "compare"
          echo ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      - name: check all
        uses: mitoma/sver-actions/exec@support-restore-only
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          phase: check
          command: |
            cargo fmt --all -- --check
            cargo clippy -- -D warnings
            cargo build
            cargo test
          # default ブランチの時だけ cache を保存する
          cache_save_enable: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          cache_key: cargo-${{ hashFiles('**/Cargo.lock') }}
          cache_restore-keys: |
            cargo-${{ hashFiles('**/Cargo.lock') }}
            cargo-
          cache_path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
