name: Continuous integration

on: [push, pull_request]

jobs:

  check-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mitoma/sver/.github/actions/setup_sver@v0.1.8
      - name: check all
        uses: mitoma/sver/.github/actions/exec_sver@v0.1.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          phase: check
          command: |
            cargo fmt --all -- --check
            cargo clippy -- -D warnings
            cargo build
            cargo test
          cache_key: cargo-${{ hashFiles('**/Cargo.lock') }}
          cache_restore-keys: |
            cargo-${{ hashFiles('**/Cargo.lock') }}
            cargo-
          cache_path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
